CREATE TYPE audio_merge_status AS ENUM (
    'Pending',
    'Processing',
    'Completed',
    'Failed'
);

CREATE TABLE audio_merge_jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name   TEXT        NOT NULL,
    model       TEXT,
    audio_url   TEXT,
    status      audio_merge_status NOT NULL DEFAULT 'Pending',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE audio_merge_segments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audio_merge_job_id  BIGINT      NOT NULL REFERENCES audio_merge_jobs(id) ON DELETE CASCADE,
    segment_index       INT         NOT NULL,
    text                TEXT        NOT NULL,
    start_time          DOUBLE PRECISION NOT NULL,
    end_time            DOUBLE PRECISION NOT NULL
);
