DROP TABLE IF EXISTS tts_audio;
DROP TYPE IF EXISTS tts_audio_status;

CREATE TYPE tts_audio_status AS ENUM (
    'Pending',
    'Processing',
    'Completed',
    'Failed'
);

CREATE TABLE tts_audios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT,
    audio_url TEXT,
    status tts_audio_status NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);